import CONFIG from './config.js';
const SESSION_KEY = 'htbpdt_asistente_session';
const state = { user: getStoredSession(), activeTab: 'dashboard', lastData: null, isLoading: false };
function getStoredSession(){ try { return JSON.parse(localStorage.getItem(SESSION_KEY)) || null; } catch { localStorage.removeItem(SESSION_KEY); return null; } }
const utils = {
  escape(v=''){ return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;'); },
  pct(v){ const n=Number(v); return Number.isNaN(n)?0:Math.max(0,Math.min(100,Math.round(n))); },
  icons(){ if(window.lucide) lucide.createIcons(); },
  badge(status=''){ const s=String(status).toUpperCase(); if(['VALIDADO','VIGENTE'].includes(s)) return 'badge badge-ok'; if(['POR_VENCER','PENDIENTE_VALIDACION'].includes(s)) return 'badge badge-warn'; if(['VENCIDO','RECHAZADO','FALTANTE'].includes(s)) return 'badge badge-error'; return 'badge badge-info'; }
};
const api = {
  async request(action,payload={}){
    if(!CONFIG.API_URL || CONFIG.API_URL.includes('XXXXXXXX')) throw new Error('Backend no configurado. Revisa config.js.');
    const controller = new AbortController(); const timeout=setTimeout(()=>controller.abort(),25000);
    try{
      ui.loader(true,'Conectando con el servidor...');
      const response = await fetch(CONFIG.API_URL,{ method:'POST', headers:{'Content-Type':'text/plain;charset=utf-8'}, body:JSON.stringify({action,payload}), signal:controller.signal });
      const text = await response.text(); let result;
      try { result = JSON.parse(text); } catch { throw new Error(`Respuesta no JSON del servidor: ${text.slice(0,120)}`); }
      if(!response.ok) throw new Error(`HTTP_${response.status}`);
      if(!result.ok) throw new Error(result.message || 'El servidor rechazó la solicitud.');
      return result;
    } catch(error){ ui.notify(api.friendly(error),'error'); console.error(`API Error [${action}]`, error); throw error; }
    finally { clearTimeout(timeout); ui.loader(false); }
  },
  friendly(error){ const msg=error?.message||''; if(error.name==='AbortError') return 'La solicitud tardó demasiado. Verifica si se guardó y vuelve a intentar.'; if(msg.includes('Failed to fetch')) return 'No se pudo conectar con Google Apps Script. Revisa permisos, despliegue, acceso público o URL del Web App.'; if(msg==='HTTP_404') return 'La URL del backend no existe o está mal copiada.'; if(msg.includes('no JSON')) return 'El backend no devolvió JSON. Revisa que el Web App esté desplegado como ejecución correcta.'; return msg || 'Ocurrió un error inesperado.'; }
};
const Components = {
  Empty(msg){ return `<div class="p-8 text-center text-slate-400 font-bold text-sm">${utils.escape(msg)}</div>`; },
  Progress(v){ const p=utils.pct(v); return `<div class="flex items-center gap-3"><div class="w-20 h-1.5 bg-slate-100 rounded-full overflow-hidden"><div class="h-full bg-emerald-500" style="width:${p}%"></div></div><span class="text-xs font-bold">${p}%</span></div>`; },
  FleetRow(u){ return `<tr class="border-b border-slate-50 hover:bg-slate-50/50"><td class="px-8 py-5 font-bold text-slate-900">${utils.escape(u.placa||u.id||'-')}</td><td class="px-8 py-5 text-sm text-slate-500">${utils.escape(u.sistema||'-')}</td><td class="px-8 py-5 text-sm font-bold text-emerald-500">${utils.escape(u.estado||'-')}</td><td class="px-8 py-5">${Components.Progress(u.compliance||u.cumplimiento||0)}</td></tr>`; },
  CrewRow(p){ return `<tr class="border-b border-slate-50 hover:bg-slate-50/50"><td class="px-8 py-5 font-bold text-slate-900">${utils.escape(p.dni||'-')}</td><td class="px-8 py-5 text-sm text-slate-500">${utils.escape(p.nombre||p.nombres||'-')}</td><td class="px-8 py-5 text-sm text-slate-500">${utils.escape(p.cargo||'-')}</td><td class="px-8 py-5">${Components.Progress(p.compliance||p.cumplimiento||0)}</td></tr>`; },
  DocRow(d){ return `<tr class="border-b border-slate-50 hover:bg-slate-50/50"><td class="px-8 py-5 font-bold text-slate-900">${utils.escape(d.tipo_documento||d.documento||'-')}</td><td class="px-8 py-5 text-sm text-slate-500">${utils.escape(d.nexo_id||d.nexo||'-')}</td><td class="px-8 py-5"><span class="${utils.badge(d.estado_cumplimiento||d.estado)}">${utils.escape(d.estado_cumplimiento||d.estado||'-')}</span></td><td class="px-8 py-5 text-sm text-slate-500">${utils.escape(d.fecha_vencimiento||d.vencimiento||'-')}</td><td class="px-8 py-5 text-sm"><button onclick="viewHistory('${utils.escape(d.documento_id)}')" class="font-bold text-[#E20613]">Historial</button></td></tr>`; }
};
const ui = {
  loader(show,msg='Procesando...'){ state.isLoading=show; const l=document.getElementById('app-loader'), m=document.getElementById('app-loader-message'); if(!l) return; if(m) m.innerText=msg; l.classList.toggle('hidden',!show); l.classList.toggle('flex',show); document.querySelectorAll('button').forEach(b=>b.disabled=show); },
  notify(message,type='info'){ let c=document.getElementById('toast-container'); if(!c){ c=document.createElement('div'); c.id='toast-container'; c.className='fixed top-6 right-6 z-[2000] space-y-3'; document.body.appendChild(c); } const t=document.createElement('div'); t.className=`bg-white border shadow-xl rounded-2xl px-5 py-4 text-sm font-bold max-w-[380px] ${type==='error'?'border-red-100 text-red-700':type==='success'?'border-emerald-100 text-emerald-700':'border-slate-100 text-slate-700'}`; t.innerText=message; c.appendChild(t); setTimeout(()=>t.remove(),5000); },
  ensureViews(){ const main=document.querySelector('main'); if(!main) return; if(!document.getElementById('view-crew')) main.insertAdjacentHTML('beforeend', `<div id="view-crew" class="view-section hidden"><div class="card-brand p-0 overflow-hidden"><table class="w-full text-left"><thead class="bg-slate-50 border-b border-slate-100"><tr class="text-[11px] font-black text-slate-400 uppercase tracking-widest"><th class="px-8 py-5">DNI</th><th class="px-8 py-5">Nombres</th><th class="px-8 py-5">Cargo</th><th class="px-8 py-5">Documentación</th></tr></thead><tbody id="crew-table-body"></tbody></table></div></div>`); if(!document.getElementById('view-docs')) main.insertAdjacentHTML('beforeend', `<div id="view-docs" class="view-section hidden"><div class="card-brand p-0 overflow-hidden"><table class="w-full text-left"><thead class="bg-slate-50 border-b border-slate-100"><tr class="text-[11px] font-black text-slate-400 uppercase tracking-widest"><th class="px-8 py-5">Documento</th><th class="px-8 py-5">Nexo</th><th class="px-8 py-5">Estado</th><th class="px-8 py-5">Vencimiento</th><th class="px-8 py-5">Acciones</th></tr></thead><tbody id="docs-table-body"></tbody></table></div></div>`); },
  switchTab(tab){ state.activeTab=tab; const titles={dashboard:'Dashboard',fleet:'Unidades',crew:'Tripulación',docs:'Documentos'}; document.getElementById('view-title').innerText=titles[tab]||'Dashboard'; document.querySelectorAll('.view-section').forEach(s=>s.classList.add('hidden')); document.getElementById(`view-${tab}`)?.classList.remove('hidden'); document.querySelectorAll('.nav-btn').forEach(b=>{b.classList.remove('bg-[#E20613]','text-white','shadow-xl','shadow-red-200'); b.classList.add('text-slate-500','hover:bg-slate-50');}); const ab=document.getElementById(`nav-${tab}`); if(ab){ab.classList.add('bg-[#E20613]','text-white','shadow-xl','shadow-red-200'); ab.classList.remove('text-slate-500','hover:bg-slate-50');} ui.render(); },
  render(){ if(!state.lastData) return; const d=state.lastData; if(state.activeTab==='dashboard') ui.renderDashboard(d.stats||{},d.units||[]); if(state.activeTab==='fleet') document.getElementById('fleet-table-body').innerHTML=(d.units||[]).length?(d.units||[]).map(Components.FleetRow).join(''):`<tr><td colspan="4">${Components.Empty('No hay unidades registradas.')}</td></tr>`; if(state.activeTab==='crew') document.getElementById('crew-table-body').innerHTML=(d.crew||[]).length?(d.crew||[]).map(Components.CrewRow).join(''):`<tr><td colspan="4">${Components.Empty('No hay tripulantes registrados.')}</td></tr>`; if(state.activeTab==='docs') document.getElementById('docs-table-body').innerHTML=(d.docs||[]).length?(d.docs||[]).map(Components.DocRow).join(''):`<tr><td colspan="5">${Components.Empty('No hay documentos registrados.')}</td></tr>`; utils.icons(); },
  renderDashboard(stats,units){ const val=utils.pct(stats.companyCompliance ?? stats.company_compliance ?? 0); document.getElementById('compliance-val').innerText=`${val}%`; const ring=document.getElementById('compliance-ring'); if(ring) ring.style.strokeDashoffset=263.89*(1-val/100); const list=document.getElementById('fleet-summary-list'); list.innerHTML=units.length?units.slice(0,3).map(u=>`<div class="flex items-center justify-between p-4 bg-slate-50 rounded-2xl"><p class="font-bold text-slate-900">${utils.escape(u.placa||'-')}</p><span class="text-xs font-bold text-emerald-500">${utils.pct(u.compliance)}%</span></div>`).join(''):Components.Empty('No hay unidades registradas.'); utils.icons(); },
  showApp(){ document.getElementById('login-modal')?.classList.add('hidden'); document.getElementById('app-container')?.classList.remove('hidden'); const e=document.getElementById('user-empresa'); if(e) e.innerText=state.user?.razon_social||state.user?.empresa||'EMPRESA'; },
  showLogin(){ document.getElementById('login-modal')?.classList.remove('hidden'); document.getElementById('app-container')?.classList.add('hidden'); }
};
window.app = {
  async login(ev){ ev.preventDefault(); const dni=document.getElementById('login-dni')?.value.trim(); const pass=document.getElementById('login-pass')?.value.trim(); if(!dni||!pass) return ui.notify('Complete DNI y contraseña.','error'); try{ const res=await api.request('login',{dni,pass}); state.user=res.data; localStorage.setItem(SESSION_KEY,JSON.stringify(res.data)); ui.showApp(); await this.refreshData(); ui.notify('Sesión iniciada correctamente.','success'); }catch{ localStorage.removeItem(SESSION_KEY); state.user=null; ui.showLogin(); } },
  async refreshData(){ if(!state.user) return ui.showLogin(); try{ const res=await api.request('getDashboard',{user:state.user}); state.lastData=res.data||{}; if(res.data?.user){state.user=res.data.user; localStorage.setItem(SESSION_KEY,JSON.stringify(state.user));} ui.showApp(); ui.render(); }catch(e){ if(String(e.message).match(/Sesión|Usuario|permiso|inactivo/i)){ localStorage.removeItem(SESSION_KEY); state.user=null; ui.showLogin(); } } },
  logout(){ if(!confirm('¿Está seguro que desea cerrar sesión?')) return; localStorage.removeItem(SESSION_KEY); state.user=null; state.lastData=null; ui.showLogin(); ui.notify('Sesión cerrada correctamente.','success'); },
  async viewHistory(documentoId){ const res=await api.request('getDocumentHistory',{documento_id:documentoId}); console.table(res.data||[]); ui.notify('Historial cargado en consola. Puede conectarse a un modal sin cambiar el diseño.','info'); }
};
window.switchTab=id=>ui.switchTab(id); window.handleLogin=ev=>window.app.login(ev); window.logout=()=>window.app.logout(); window.refreshData=()=>window.app.refreshData(); window.viewHistory=id=>window.app.viewHistory(id);
document.addEventListener('DOMContentLoaded', async()=>{ ui.ensureViews(); utils.icons(); if(state.user){ ui.showApp(); await window.app.refreshData(); } else ui.showLogin(); });
