const CONFIG = {
  API_URL: "https://script.google.com/macros/s/AKfycbw5HblCVk5JP6RaCDKQAErzHEm06iceGjIrRl0UTUUBOXLZ4wUfnH1nxZd5aNlkBQVe/exec",

  PORTAL: "VALIDADOR",

  STATUS: {
    PENDIENTE_VALIDACION: "PENDIENTE_VALIDACION",
    VALIDADO: "VALIDADO",
    OBSERVADO: "OBSERVADO",
    RECHAZADO: "RECHAZADO"
  }
};

export default CONFIG;
