const CONFIG = {
  API_URL: "https://script.google.com/macros/s/AKfycbxZDlFIof5Xv1FDt3XGu4tSITTIOa8Ue8vh6ew8lzPyYXFS3jP9kBbAtwoY2BgyC5XJ/exec",

  PORTAL: "VALIDADOR",

  STATUS: {
    PENDIENTE_VALIDACION: "PENDIENTE_VALIDACION",
    VALIDADO: "VALIDADO",
    OBSERVADO: "OBSERVADO",
    RECHAZADO: "RECHAZADO"
  }
};

export default CONFIG;
