const CONFIG = {
  API_URL: "https://script.google.com/macros/s/AKfycbx8MANknvdt7AYxBHIBSNc1f0kGYjE-lIC9AM1LBjPMi6xLYfulFjZu927GSKBDS_eC/exec",

  PORTAL: "VALIDADOR",

  STATUS: {
    PENDIENTE_VALIDACION: "PENDIENTE_VALIDACION",
    VALIDADO: "VALIDADO",
    OBSERVADO: "OBSERVADO",
    RECHAZADO: "RECHAZADO"
  }
};

export default CONFIG;
